### PR TITLE
Remove use of np.asscalar for compatibility with numpy>=1.23

### PR DESCRIPTION
**Pull request by wxmerkt**
Cf. https://github.com/numpy/numpy/pull/20414

Required for unittests to pass if numpy is newer than 1.22

### CODE REVIEW

**Review by cmastalli — COMMENTED** [review]
Are you sure this works for versions lower than 1.22?

**Comment by wxmerkt** [comment]
Yes - I just downgraded to 1.18 and all tests passed

**Comment by cmastalli** [comment]
> Yes - I just downgraded to 1.18 and all tests passed

Thanks for double checking. Do you know why the ROS-CI jobs are not passing?

**Comment by wxmerkt** [comment]
I believe because the CMake fix that Guilhem proposed hasn't been merged yet (it cannot find Python2 on 18.04). I'll deactivate the 18.04 builds for now

**Comment by wxmerkt** [comment]
That said, it also failed to find Python on 18.04 in https://github.com/loco-3d/crocoddyl/pull/1084 where that fix would be applied. This makes me think it may be broken on 18.04 without explicitly pointing `-DPYTHON_EXECUTABLE=...`. I dont have access to an 18.04 system and will leave the CI case turned of for now. If we have someone using catkin on 18.04 with issues we can revisit it then.

**Comment by cmastalli** [comment]
Let's wait to resolve https://github.com/loco-3d/crocoddyl/pull/1084, and then apply those changes.

**Comment by cmastalli** [comment]
Is there anything needed from https://github.com/loco-3d/crocoddyl/pull/1084 to merge this PR?

**Comment by wxmerkt** [comment]
No, and to avoid conflicts in possible rebases I suggest we merge this PR, then commit the suggestions in the review comments of the v2 PR where appropriate, then merge the v2 PR once we hear back from Nicolas and then address any CI issues or other issues if they come up in follow-up PRs

**Pull request merged**
